# Generated by Django 3.1.6 on 2021-03-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(default=53.9),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(default=27.5667),
        ),
    ]
